---
config:
  theme: dark
  layout: elk
---
flowchart TB
 subgraph repo_docs["Documentation Repository"]
        repo_docs_desc["Description<br>Data"]
        repo_docs_cons["Constraints<br>Data"]
        repo_docs_req["Requirements<br>Data"]
  end
 subgraph repo_diags["Diagram Repository"]
        repo_diags_context["Context<br>Data"]
        repo_diags_container["Container<br>Data"]
        repo_diags_component["Component<br>Data"]
  end
 subgraph repo["Project Repository"]
        repo_docs
        repo_diags
  end
 subgraph archon["Archon"]
        arch_agent["Architect<br>Agent System"]
        synth_agent["Synthetic<br>Agent System"]
        doc_rules["Documentation Ruleset<br>Software System"]
        diags_agent["Diagram<br>Agent System"]
        diags_rules["Diagram Ruleset<br>Software System"]
  end
    arch_agent -- Design sequence with state --> synth_agent
    synth_agent -- Visualize textual report --> diags_agent
    diags_agent -- Verify rule consistency --> diags_rules
    diags_rules --> diags_agent
    synth_agent -- Verify syntactic integrity --> doc_rules
    doc_rules --> synth_agent
    dev["Architect<br>Person"] -- Run design iteration --> arch_agent
    dev <-- Read and verify --> repo
    repo_docs -- Get state --> arch_agent
    repo_diags -- Get state --> arch_agent
    synth_agent -- Push documentation --> repo_docs
    diags_agent -- Push diagrams --> repo_diags