---
config:
  theme: dark
  layout: elk
---
flowchart TB
 subgraph definitions["Definitions<br>[Data]"]
        defs_desc["Description<br>[Data]<br>System concept, overview, goals and details"]
        defs_cons["Constraints<br>[Data]<br>Mandatory technologies, requirements and limits"]
        defs_req["Requirements<br>[Data]<br>System conditions, defined behaviors and attributes"]
        defs_us["User Stories<br>[Data]<br>User stories, requirements and constraints"]
  end
 subgraph diagrams["Diagrams<br>[Data]"]
        diags_cntx["Context<br>[Data]<br>System in its environment, users and dependencies"]
        diags_cntr["Container<br>[Data]<br>High-level technology building blocks as units"]
        diags_cmpt["Component<br>[Data]<br>Structure of modules/controllers and collaborations"]
  end
 subgraph artifacts["Artifacts<br>[Data]"]
        artf_transcript["Transcripts<br>[Data]<br>Design records as message history"]
        artf_analysis["Analysis<br>[Data]<br>Design stage and iteration analysis results"]
        artf_views["View<br>[Data]<br>Text-based diagram representation"]
        artf_queue["Queue<br>[Data]<br>Queue of generation tasks"]
  end
 subgraph repo["Project Repository<br>[Software System]"]
        definitions
        diagrams
        artifacts
  end
 subgraph archon["Archon<br>[Container]"]
        expert_agent["Expert Agent<br>[Component]<br>Solution and detail architect, processing system brief"]
        synth_agent["Synthetic Agent<br>[Component]<br>Define nodes and edges"]
        doc_rules["Documentation Ruleset<br>[Component]<br>Methodology and semantic criteria"]
        diags_agent["Diagram Agent<br>[Component]<br>Draw diagrams"]
        diags_rules["Diagram Ruleset<br>[Component]<br>Diagram guidelines and structural criteria"]
  end
    expert_agent -- "Records the history of messages and prompts" --> artf_transcript
    expert_agent -- "Build architectural desigion for stage" --> artf_analysis
    expert_agent -- "Execute design sequence with state" --> synth_agent
    architect["Architect/Developer<br>[Person]<br>System Vision"] -- "Run design iteration according to stage" --> expert_agent
    defs_req -- "Introduces requirements for design decisions" --> expert_agent
    defs_cons -- "Defines project constants and variables" --> expert_agent
    defs_desc -- "Establishes the system concept and the required solution" --> expert_agent
    defs_us -- "Establishes the user stories" --> expert_agent
    diagrams -- "Get existing diagrams state" --> expert_agent
    artf_analysis -- "Pull architectural desigion to describe" --> synth_agent
    synth_agent -- "Verify synthetic integrity" --> doc_rules
    doc_rules --> synth_agent
    synth_agent -- "Storing text based view" --> artf_views
    synth_agent -- "Create task for exact view to visualize" --> artf_queue
    synth_agent -- "Records the history of messages and prompts" --> artf_transcript
    architect -- "Set project and system requirements" --> defs_req
    architect -- "Limit decision shift" --> defs_cons
    architect -- "Build core concept and description of the product" --> defs_desc
    architect -- "Verify assumptions according with design" --> artf_transcript
    architect -- "Track desigion changes in history" --> artf_analysis
    diags_agent -- "Pull opened task to visualize" --> artf_queue
    artf_queue --> diags_agent
    artf_views -- "Fetch text based view" --> diags_agent
    diagrams -- "Get node and edge names of existing state" --> synth_agent
    diags_agent -- "Verify diagram consistency" --> diags_rules
    diags_rules --> diags_agent
    diags_agent -- "Push diagrams depends on stage" --> diagrams