---
config:
  theme: dark
  layout: elk
---
flowchart TB
 subgraph repo["Project Repository<br>[Software System]"]
        definitions["Definitions<br>[Data]<br>Description, user stories, constraints and requirements"]
        artifacts["Artifacts<br>[Data]<br>Technical docs, queue and backlogs"]
        diagrams["Diagrams<br>[Data]<br>System Context, Containers, Components, Code"]
  end
    archon_agent["Archon Agent<br>[Container]"] -- Visualize project decisions described in text --> diagrams
    archon_agent -- Verify project consistency, reduce architectural drift --> definitions
    archon_agent -- Reflect the design workflow within the plan and push artifacts --> artifacts
    architect["Architect/Developer<br>[Person]<br>Project Vision"] -- Run design iteration according to stage --> archon_agent
    architect -- Define project concept and set requirements with constraints --> definitions
    architect -- "Keep up-to-date mental model across project architecture" --> artifacts
    architect -- Trace project boundaries and design decisions --> diagrams